### ISSUE TITLE
Validating Objects inside an Array

### ISSUE THREAD

**Issue by vasiliyb** [geraintluff/tv4#161]
Folks,
  To validate objects inside and array, is this the most straightforward approach? 

```
var schema = require('../schemas/foo.json');
_.each(postedArray, function (object) {
     var valid = tv4.validate(body, schema);
      if(!valid){
        // send a 404
      }
});
```

Thanks!

**Comment by elyas-bhy** [comment]
You can use the [array type](http://json-schema.org/latest/json-schema-core.html#anchor8) in your schema as follows:

```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "foo",
  "type": "array",
  "items": {
    "field1": {
      "type": "string"
    },
    "field2": {
      "type": "string"
    }
  }
}
```
  
Or, if you want to preserve the `foo.json` schema because you are using it elsewhere, you can define a new schema for your array and use `foo` as a reference for your items, as such:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "bar",
  "type": "array",
  "items": {
    "$ref": "foo.json#/foo"
  }
}
```

**Comment by vasiliyb** [comment]
thanks!
