### ISSUE TITLE
$ref to array doesn't work

### ISSUE THREAD

**Issue by mizchi** [geraintluff/tv4#218]
expect: `{"a": "a"}`
to `{"a": "b"}`

It doesn't pass both valid and invalid

```
{
  "enum": {
     "$ref": "#/enums/a"
  },
  "enums": {
     "a": ["a"]
  }
};
```

It works

```
{
  "$ref": "#/enums/a",
  "enums": {
     "a": {
         "enum": {
             "a": ["a"]
         }
     }
  }
}
```

(but I have no confidence it is in jsonschema specs)

**Comment by geraintluff** [comment]
The values inside `enum` can't be references.  The only place where a reference can be used is in place of a schema.

So, you can use references for the values of keywords like `items` or `additionalProperties`, because their values are schemas.  However, keywords with non-schema values (like `enum` or `maxLength`) don't work.  Sorry!
